import Head from 'next/head'

export default function Home() {
   return (
      <div className="container mx-auto">
         <Head>
            <title>Strapi Auth Jwt</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <h1 className="text-violet-700 font-bold text-2xl">Hello irfan ramdani.</h1>


      </div>
   )
}
